### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by romain10009** [mbenzenhoefer/ngx-bootstrap-growl#10]
Hi, I'm getting an error : 

`
ERROR in node_modules/ngx-bootstrap-growl/node_modules/rxjs/Subject.d.ts(24,5): error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator:
Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.
node_modules/ngx-bootstrap-growl/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts(44,5): error TS2416: Property 'lift' in type 'WebSocketSubject<T>' is not assignable to the same property
in base type 'AnonymousSubject<T>'.
  Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
    Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
      Types of property 'operator' are incompatible.
        Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
          Type 'R' is not assignable to type 'T'.
`

**Comment by walalm** [comment]
1. Open a command prompt (let's suppose you are using windows)
2. cd  node_modules 
3. cd ngx-boostrap-growl
4. Modify your  package.json to the latests versions of dependencies, mine looks like this (partially pasted file):
` "dependencies": {
    "rxjs": "6.2.2",
    "zone.js": "^0.7.6"
  },
  "deprecated": false,
  "description": "Service to show growl in Angular >= 2 with Twitter Bootsrap 4",
  "devDependencies": {
    "@angular/common": "^6.1.3",
    "@angular/compiler": "^6.1.3",
    "@angular/compiler-cli": "^6.1.3",
    "@angular/core": "^6.1.3",
    "@types/core-js": "^2.5.0",
    "@types/node": "^10.7.1",
    "copyfiles": "^2.0.0",
    "tslint": "^5.11.0",
    "typescript": "2.7.2"
  },`
5. Run this command: npm update

After that your should be working fine!
Hope that helps

**Comment by SainathReddy-GNV** [comment]
@walalm  I am still getting same error even after doing what you mentioned above. Can you please elaborate what we should do to make it work on Angular 6?
